INSERT INTO DOG(BREED, NAME, ORIGIN) VALUES ('BREED 1', 'NAME 1', 'ORIGIN 1');
INSERT INTO DOG(BREED, NAME, ORIGIN) VALUES ('BREED 2', 'NAME 2', 'ORIGIN 2');
INSERT INTO DOG(BREED, NAME, ORIGIN) VALUES ('BREED 3', 'NAME 3', 'ORIGIN 3');
INSERT INTO DOG(BREED, NAME, ORIGIN) VALUES ('BREED 4', 'NAME 4', 'ORIGIN 4');
INSERT INTO DOG(BREED, NAME, ORIGIN) VALUES ('BREED 5', 'NAME 5', 'ORIGIN 5');